{% set name = "allantools" %}
{% set version = "2024.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c4380c74de834ac869aefc899038e784ef1dd396370be89d6836abffbe484289

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpydoc
    - pytest-runner
    - setuptools
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - allantools
    - allantools.dataset
    - allantools.ci
    - allantools.noise
    - allantools.noise_kasdin
    - allantools.plot
    - allantools.realtime

about:
  home: https://github.com/aewallin/allantools
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'Allan deviation and related time & frequency statistics library in Python'
  description: |
    A python library for calculating Allan deviation and related time & frequency statistics.
    LGPL v3+ license.
  doc_url: https://allantools.readthedocs.io
  dev_url: https://github.com/aewallin/allantools

extra:
  recipe-maintainers:
    - aewallin
